defaults: &defaults
  module_prefs:
    title: "Gadget"
    author: "Calvin"
    author_email: "calvin@example.com"
  requires:
    - opensocial-0.8
    - opensocial-data
    - opensocial-templates
    - dynamic-height
    - settitle
    - views

development:
  <<: *defaults
  appid: 1234567890

test:
  <<: *defaults
  appid: 1234567890

production:
  <<: *defaults
  appid: 1234567890
